services:
  - type: web
    name: tcj-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_KEY
        sync: false
      - key: FOLDER_ID
        sync: false

